spring.application.name=skillshare-backend

server.port=8080

spring.data.mongodb.uri=mongodb+srv://Chamodya:Chamodya897@cluster0.gqv5t.mongodb.net/skillshare?retryWrites=true&w=majority&appName=Cluster0

jwt.secret=VGhpc0lzQVNlY3VyZVNlY3JldEtleUZvckpXVFRva2VuR2VuZXJhdGlvbg==
jwt.expiration=86400000

cloudinary.cloud-name=YOUR_CLOUD_NAME

cloudinary.api-key=YOUR_API_KEY

cloudinary.api-secret=YOUR_API_SECRET

spring.mail.host=smtp.gmail.com
spring.mail.port=587

spring.mail.username=chamodyaishani10@gmail.com
spring.mail.password=YOUR_APP_PASSWORD

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

springdoc.swagger-ui.path=/swagger-ui.html